version: '3.4'

services:
  mfcrudpremium:
    image: mfcrudpremium
    build:
      context: crud-canciones-premium/mf-crud-premium
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4202:4202
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
